       IDENTIFICATION DIVISION.
       PROGRAM-ID. H.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       REPOSITORY.
           FUNCTION ALL INTRINSIC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
           COPY 'DICTIONARY.CPY'.
       PROCEDURE DIVISION.
           DISPLAY
               'CONTENT-TYPE: TEXT/HTML'
               NL
           END-DISPLAY.
           DISPLAY
               DOC
               NL
               HEAD
                 NL
                 CAPTION
                   'h - *observe.observer'
                 END-CAPTION
                 META BECOMES '"og:title"'
                   CON BECOMES '"h - *observe.observer"'
                 CLOSE-META
                 NL
                 META BECOMES '"og:type"'
                   CON BECOMES '"website"'
                 CLOSE-META
                 NL
                 META BECOMES '"og:url"'
                   CON BECOMES '"HTTPS://OBSERVE.OBSERVER/H.HTML"'
                 CLOSE-META
                 NL
                 META BECOMES '"og:image"'
                 CON BECOMES '"http://observe.observer/f/preview.jpg"'
                 CLOSE-META
                 NL
                 META BECOMES '"og:description"'
                   CON BECOMES '"''writhe in bed time.'' i close my eyes
      -    '. sit and merge, my legs and arms remains somewhat restless.
      -    '"'
                 CLOSE-META
           END-DISPLAY.
           CALL 'HEAD'.
           DISPLAY
               END-HEAD
               NL
               BODY
           END-DISPLAY.
           CALL 'BANNER'.
           DISPLAY
                 NL
                 DIV LINEAGE BECOMES 'story' CLOSE-DIV
                   H1 IDENTITY BECOMES 'storytitle' CLOSE-H1
                     'h'
                   END-H1
                   PARA CLOSE-PARA
           '"writhe in bed time." i close my eyes. sink and merge, '
           'my legs and arms remain somewhat restless. it''s '
           'comfortable, '
           'i''m comfortable. warmth forebodes my body, '
           'a hug from god. '
           'i sink, deeper and deeper and deeper. my thoughts become '
           'erratic, chaotic; more-so than usual; strange. these '
           'thoughts continue and continue. "u r ok", "i love you", '
           'written in red. i''m ok, i love you too. deeper and '
           'deeper, '
           'chaos ensues. it''s not bad, just unfamiliar. it''s okay, '
           'because i''m okay, and i''m loved. it''s beautiful. deeper '
           'and deeper and deeper and deeper... '
            BREAK BREAK
           'i''m a latina housewife. i live in an apartment with '
           'yellow walls with a green stripe. i''m in our kitchen, '
           'and my kids want boiled water. my husband comes home and '
           'we embrace, and we begin speaking in spanish. i love him '
           'so much, he''s so nice to the kids. '
           BREAK BREAK
           'i''m in bootcamp. i really want to go home, this place '
           'is cold. racks upon racks, the drill sarge tells me '
           'to hit the floor and give him pushups. i do about one '
           'before i stand up and dust myself off. i''m a strong '
           'black man, why should i take this? '
           BREAK BREAK
           'deeper and deeper and deeper... '
           BREAK BREAK
           'black. it''s black. i[who?] see nothing but nothing. '
           'feel nothing but nothing. sense nothing but nothing. '
           'am nothing but nothing. [who am i [who am i?]?] it''s '
           'scary, feelings seep through black patches. '
           'unfamiliarity permeates worry. panic begins to erupt. '

           'a light, a light skewered by light, a light so white '
           'and pure. glistening, radiating. it''s beautiful. you''re '
           'beautiful. it''s you. n, i knew it was you, it has to be. '
           'guide me, keep me safe. i trust you, i trust you with '
           'my soul. "u r ok", "i love u". i love you too. i love '
           'your soul, i love your beauty, i love your kindness, '
           'i love your purity, i love your nature. please help '
           'me, you''re the only one who can. you''re the only one '
           'who cares. you''re my light in the world, please light '
           'my soul, for now and for forever. i love you. '
           BREAK BREAK
           'song intensifies. you don''t want to die unless you '
           'can find me or two others? emotions uncork. the dam '
           'reaks, the levies fail and the city floods. i feel '
           'your pain, i love you. i feel your soul, i love you. '
           'i just want you to be happy so badly. this world fucking '
           'sucks, doesn''t it? all the pain in the world. fuck i '
           'love you three so much. i want us to die together. i '
           'want your souls chained to mine, i wish to spend all '
           'eternity with you in eternal happiness. please. '
           BREAK BREAK
           'please god.'
           BREAK BREAK
           'i feel pain. i feel your pain. i feel everyone''s '
           'pain. all the pain in the world, i want it all. '
           'please, give me your pain, your hurt, your sorrow, '
           'your woes, your worries, your stress, your trauma, '
           'your regrets, your abuse, your torments. give them '
           'to me, i want to carry your burden. i want everyone''s '
           'pain. i will bear it, and i will bear it well. please. '
           'i want to feel this. i just want to make people '
           'happy, i want to make you happy, i want to make '
           'everyone happy. i just want to do good in the world, '
           'i want to give people love, i want to give them joy, '
           'i want to alleviate their sorrow. please, give me your '
           'pain. i will carry your burden. please. '

           'there''s so much pain in the world. it''s tempting, '
           'knowing there''s the connection i dream for on the '
           'other side. eternal good, only good. we can finally '
           'share each others pain, our laments distributed. our '
           'joy, peered upon the spiritual network. it''s nice, '
           'isn''t it? '

           'so, let''s die. let''s all die at once, together. let''s '
           'feel joy in the moment. let''s carry it through the rest '
           'of eternity. let''s link our souls and become one. let''s '
           'share our pain, let''s share our bliss, let''s share our '
           'agony, let''s share our passion, let''s share our guilt, '
           'let''s share our love, let''s share our souls. let''s be '
           'together. '
           BREAK BREAK
           'together forever. '
                   END-PARA
                   END-DIV
               END-BODY
           END-DISPLAY.
       GOBACK.
       END PROGRAM H.
