       IDENTIFICATION DIVISION.
       PROGRAM-ID. INDEX.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       REPOSITORY.
           FUNCTION ALL INTRINSIC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
           COPY 'DICTIONARY.CPY'.
       PROCEDURE DIVISION.
           DISPLAY
               'CONTENT-TYPE: TEXT/HTML'
               NL
           END-DISPLAY.
           DISPLAY
               HEAD
                 NL
                 CAPTION
                   'stories - *observe.observer'
                 END-CAPTION
                 META PROP BECOMES '"og:title"'
                      CON BECOMES '"stories - *observe.observer"'
                 CLOSE-META
                 NL
                 META PROP BECOMES '"og:type"'
                      CON BECOMES '"website"'
                 CLOSE-META
                 NL
                 META PROP BECOMES '"og:url"'
                      CON BECOMES '"HTTPS://OBSERVE.OBSERVER/INDEX.HTML"
      -    ''
                 CLOSE-META
                 NL
                 META PROP BECOMES '"og:image"'
                     CON BECOMES '"http://observe.observer/f/preview.jpg
      -    '>"'
                 CLOSE-META
                 NL
                 META PROP BECOMES '"og:description"'
                      CON BECOMES 'i dont want to die. they will never u
      -    'nderstand what we want, it''s impossible. i want it, you wan
      -    't it.'
                 CLOSE-META
           END-DISPLAY.
           CALL 'HEAD'.
           DISPLAY
               END-HEAD
               NL
               BODY
           END-DISPLAY.
           CALL 'BANNER'.
           DISPLAY
                 STYLE
                   '.storieslink {FONT-WEIGHT:BOLD; FONT-STYLE:ITALIC}'
                 END-STYLE
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"M.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'm'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'why can''t people be who they want to be? '
           'i can''t accept the world as it is. i wish for a pure '
           'world, a world where people could be beautiful. '
           'i want you to be yourself, i don''t want you to hold back. '
           'i know it''s hard, maybe impossible at times. it''s a pain '
           'i can''t face. '
           'there''s so much potential, i''ve felt and seen it that '
           'potential feels limitless ... '
                   LINK URL BECOMES '"M.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"L.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'l'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'she feels pain. he feels pain. "what am i? am i real? '
           'what am i?" it''s hard. she wants to be herself, why '
           'can''t she? she is, but she''s not. everyone should be. '
           'it''s hard, society is cruel; a conveyer belt. the '
           'assembly line pushing drone, drone everything. she '
           'wants to be beautiful, but how? what is beautiful? '
           'beautiful to her is atypical, is atypical good? ... '
                   LINK URL BECOMES '"L.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"K.COB"' CLOSE-DIV
                     H1 CLOSE-H1
                       'k'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'i just want us to be happy. im happy. not really? dont '
           'know, hard to say. sometimes im happy, sometimes im '
           'miserable. unfulfilled. i want you to be happy. i know '
           'why you''re not, and it''s ok. i want to make you happy; '
           'i want to fix you. it''s not my job, but i have to do '
           'it. it''s in my heart, it''s in my soul. i just want '
           'to see you smile. i want to see you comfortable. '
           'you will be, i promise. just let me, ok? ... '
                   LINK URL BECOMES '"K.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"J.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'j'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'i dont want to die. they will never understand what '
           'we want, it''s impossible. i want it, you want it; '
           'but it is a pipedream. you can''t fault "normal" people '
           'for thinking we are crazy; but they will know in death '
           'what we mean. they will feel our thoughts and '
           'desires, just like we want ... '
                   LINK URL BECOMES '"J.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"I.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'i'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'its stressful. i just want it to stop. i get urges, '
           'i get angry, i get frustrated, i get depressed; an '
           'angry sadness, a sadness i cant love. why does it '
           'bother me so much? i couldnt even fucking move '
           'breathing heavily. i gripped nothing as hard i '
           'could grip. i saw myself bashing my ... '
                   LINK URL BECOMES '"I.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"H.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'h'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           '"writhe in bed time." i close my eyes. sink and merge, my '
           'legs and arms remain somewhat restless. it''s comfortable, '
           'i''m comfortable. warmth forebodes my body, a hug '
           'from god ... '
                   LINK URL BECOMES '"H.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     H1 CLOSE-H1
                       'n'
                     END-H1
                   END-DIV
                   PARA CLOSE-PARA
           'we''ll live forever, we''ll die together. we''ll become '
           'one, '
           'together forever. our heart, our soul. our love, our pain. '
                   BREAK BREAK
           'i love you so much.'
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"G.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'g'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'swallow and let''s go. let''s wait a bit, the calm '
           'before the storm? i don''t know, it''s been a long time, '
           'maybe never? wait. still waiting. oh, there you are. '
           'familiar feeling through arms and legs, it''s okay. '
           'huh, words split in 2. words split stretched. '
           'words betray comprehencmrozwkefs- i''m slipping back '
           'i''m falling through fuck i don''t want this? i don''t '
           'want this? i don''t want this? ... '
                   LINK URL BECOMES '"G.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"F.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'f'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'where one world ends, another begins. locked away, '
           'infosphere grows exponential. social paradigm shifts '
           'from physical to transpersonal, unveiling the way to '
           'vast webs of communication. small colonies exist there; '
           'pilgrims, leading a way to the new existence ... '
                   LINK URL BECOMES '"F.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"E.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'e'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'curled up touch loss don''t know. it''s here and '
           'material, light warm candles inside. love smoke '
           'empathy embers, slips into bed. i''m here, i''m '
           'comfortable. closed eyes, whisked away. green tendril '
           'blue tendril: cuts black, immaterial; soul apparent ... '
                   LINK URL BECOMES '"E.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"D.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'd'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'Weird! Nothing going on here. Anybody else see who '
           'got married? Anybody see those celebrities break up? '
           'Did you see those (SAME SEX!) celebrities making out? '
           'It''s a crazy world we live in, it''s hot, fast, sleek '
           'and changing; here today gone tomorrow ... '
                   LINK URL BECOMES '"D.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"C.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'c'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'maybe ill delete this when i wake up or maybe i wont '
           'idk i feel like im sobered up to own pressing on this '
           'one, maybe ill be really embarrassed. '
                BREAK
                BREAK
           'coming down off a very strength 25e trip which usually '
           'makes me want to write things even if its something g*y '
           'like a """blog post""" ... '
                   LINK URL BECOMES '"C.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"GBP.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'gbp'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'today the thoughts ablaze, everyday the same way. '
           'ruminations parallaxed through internal nocs. electronic '
           'escape puts the mind to ease, for this a debt unpaid. '
           'in the roots insects burrow, an aura of agony ... '
                   LINK URL BECOMES '"GBP.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 DIV LINEAGE BECOMES 'listing' CLOSE-DIV
                   DIV LINEAGE BECOMES 'title' CLOSE-DIV
                     LINK URL BECOMES '"B.COB"' CLOSE-LINK
                     H1 CLOSE-H1
                       'b'
                     END-H1
                     END-LINK
                   END-DIV
                   PARA CLOSE-PARA
           'Friday, August 15th, 2003. 10 o''clock PM EST (7 o''clock '
           'PM PST). Dark night (#2E2E2E, https://www.color-hex.com/ '
           'color/2e2e2e) and a moon whole (#F3F3F3, https://www.color '
           '-hex.com/color/f3f3f3) I wandered to the retention pond '
           '(Lat: 28.688283, Long: -81.459296), murky water (approx'
           '#004931, https://www.color-hex.com/color/004931) '
           'whereupon I stumbled a noise beckon''d ... '
                   LINK URL BECOMES '"B.COB"' CLOSE-LINK
                     'Continue'
                   END-LINK
                   END-PARA
                 END-DIV
                 MIDDLE
                   IMAGE SRC BECOMES '"F/LOGO.PNG"' CLOSE-IMAGE
                 END-MIDDLE
                 MIDDLE
                   LINK URL BECOMES '"https://github.com/ObserveObserver
      -    '/observeobserver.github.io/blob/master/src/observeobserver.p
      -    'l"'
                   CLOSE-LINK
                     'Written in OpenCOBOL'
                   END-LINK
                 END-MIDDLE
               END-BODY
           END-DISPLAY.
       GOBACK.
       END PROGRAM INDEX.
